socialDistribution/project/urls.py
"""
Module containing URL patterns for the project app.

Authors:
    Kai Luedemann
    Anjelica Marianicz
    James Schaefer-Pham
    Sashreek Magan
    Shalomi Hron
Date: 2023-11-18

Copyright 2023 RESTless Clients
Licensed under the MIT License

Sources:
"""
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import views, viewsets
from rest_framework import permissions, routers
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from .viewsets import AuthorViewSet, PostViewSet

app_name = 'project'

# Reference: https://www.jasonmars.org/2020/04/22/add-swagger-to-django-rest-api-quickly-4-mins-without-hiccups/
schema_view = get_schema_view(
    openapi.Info(
        title="Grapevine API",
        default_version='v1',
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = routers.SimpleRouter()
router.register("users", viewsets.UserViewSet, basename="user")
router.register("authors", viewsets.AuthorViewSet, basename="author")
router.register("posts", viewsets.PostViewSet, basename="post")
router.register("follow-requests", viewsets.FollowRequestViewSet, basename="follow-request")
router.register("comments", viewsets.CommentViewSet, basename="comment")


urlpatterns = [
  # Swagger OpenAPI documentation
  path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
  path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
  # Stream
  path('<str:username>/stream', views.StreamView.as_view(), name='stream'),
  # Author
#   path('authors/<str:pk>', views.AuthorView.as_view(), name="author"),
  # Post

  # path('posts/<str:pk>', views.PostView.as_view(), name="post"),

  path('create-post', views.CreatePostView.as_view(), name='create-post'),
  path('edit-post/<str:pk>', views.EditPostView.as_view(), name='edit-post'),
  # Profile
  path('authors/<str:pk>', views.ProfileView.as_view(), name='profile'),
  # Edit Profile
  path('edit/', views.profile_edit, name='profile_edit'),
  # Homepage
  path('', views.stream_view, name='home'),
  # Signup


  # Author APIs
  path('api/authors/', views.AuthorAPIView.as_view(), name='get_authors'),
  path('api/authors/<str:pk>/', views.UpdateAuthorApiView.as_view(), name='author_api'),
  # Post APIs
  path('api/authors/<str:pk>/posts/', views.PostsAPIView.as_view(), name='posts_api'),
  path('api/authors/<str:pk>/posts/<str:post_id>', views.SinglePostApiView.as_view(), name='single_post_api'),
  # Inbox API
  path('api/authors/<str:pk>/inbox', views.InboxAPIView.as_view(), name='inbox_api'),
  # Node API
  path('api/nodes/', views.NodeAPIView.as_view(), name='node_api'),

  # Likes
  path('authors/<str:author_id>/posts/<str:pk>/like/', views.like_post, name='like_post'),
  path('post/<str:pk>/likeCom/', views.like_comment, name='like_comment'),
  # Comments
  path('authors/<str:author_id>/posts/<str:pk>/comment/', views.add_comment, name='add_comment'),
  # Follow
  path('authors/<str:pk>/follow/', views.FollowRequestSendView.as_view(), name='follow'),
  # Accept follow request
  path('followrequest/<str:pk>/accept/', views.accept_follow_request, name="accept_follow"),
  # Decline follow request
  path('followrequest/<str:pk>/decline/', views.decline_follow_request, name="decline_follow"),
  # Decline follow request
  path('author/<str:pk>/unfollow/', views.unfollow, name="unfollow"),
  #path('search/', views.SearchAuthors.as_view(), name='search'),
  # Follow API
  path('api/authors/<str:pk>/followers/', views.FollowersAPIView.as_view(), name="get_followers"),
  path('api/authors/<str:pk>/followers/<str:follower_id>', views.FollowerAPIView.as_view(), name="api_follower"),
  path('api/authors/<str:pk>/inbox/followrequest', views.FollowRequestAPIView.as_view(), name="api_follow_request"),
  # Comment API
  path('api/authors/<str:author_id>/posts/<str:post_id>/comments/', views.CommentAPIView.as_view(), name="comment_api"),
  # Like API
  path('api/authors/<str:author_id>/posts/<str:post_id>/likes', views.PostLikeAPIView.as_view(), name="api_post_likes"),
  path('api/authors/<str:author_id>/posts/<str:post_id>/comments/<str:comment_id>/likes', views.CommentLikeAPIView.as_view(), name="api_comment_likes"),
  path('api/authors/<str:author_id>/liked', views.UserLikedAPIView.as_view(), name="api_user_liked"),
  # Delete post
  path('post/<str:pk>/delete', views.delete_post, name="post_delete"),
  path('api/local/', include(router.urls)),
  path("api/local/signup/", views.SignUpView.as_view(), name="signup"),
  # Share post
  path('api/posts/<str:post_id>/share', views.SharePostView.as_view(), name="share_post"),
  # Notifications API
  path('api/authors/<str:author_id>/notifications', views.NotificationAPIView.as_view(), name="notifications_api"),
  
  path('api/search', views.SearchAuthors.as_view(), name="search_authors"),
  path('api/authors/<str:pk>/profile', views.ProfileAPIView.as_view(), name="profile_api"),
  path('api/authors/<str:author_id>/posts/<str:post_id>/create_comment', views.AddCommentView.as_view(), name="create_comment")
]

socialDistribution/socialDistribution/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from project.views import CheckUsernameView

urlpatterns = [
    path('', include('project.urls')),
    path('api/local/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/local/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("api/local/check-username/", CheckUsernameView.as_view(), name="check-username"),
    path('admin/', admin.site.urls),
    path("", include("django.contrib.auth.urls")),


] + static('assets/', document_root=settings.FRONTEND_ASSETS)

socialDistribution/project/models.py
"""
Module containing Django model declarations

Authors:
    Shalomi Hron
    James Schaefer-Pham
    Kai Luedemann
Date: 2023-11-16

Copyright 2023 RESTless Clients
Licensed under the MIT License

Sources:
"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

import uuid


class Author(models.Model):
    """
    A class representing a user of the social network.
    Can create posts, comments, and likes, and interact with (follow) other authors.

    Attributes:
        type - the type field to use for serialization
        user - the Django user that the author is associated with
        id - the UUID primary key for the author
        url - a link to the author's profile
        host - the address of the node hosting the author
        displayName - the author's username
        github - the author's GitHub profile
        profileImage - a link to a profile image to use
        bio - a short description of the author
        streamPosts - the posts that appear in the authors inbox
        following - the authors that this user is following
    """

    type = models.CharField(max_length=20, default="author")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    url = models.URLField(max_length=200, blank=True, null=True)
    host = models.CharField(max_length=200, default="127.0.0.1")  # TODO add conditional for localhost if not deployed
    displayName = models.CharField(max_length=50)
    github = models.URLField(max_length=200, blank=True, null=True)
    profileImage = models.URLField(max_length=200, default="https://i.imgur.com/k7XVwpB.jpeg")

    bio = models.CharField(max_length=1000, blank=True)

    streamPosts = models.ManyToManyField("Post", related_name="inboxes", blank=True)  # TODO wwe need to refactor this to add likes and comments
    following = models.ManyToManyField("Author", related_name='followers', symmetrical=False, blank=True)

    def get_url(self):
        return self.url
    
    def __str__(self):
        return self.displayName

class Notification(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    message = models.CharField(max_length=500)
    link = models.URLField(max_length=500)
    timestamp = models.DateTimeField(default=timezone.now, blank=True)

class FollowRequest(models.Model):
    """
    A class representing a follow request sent by one author to another.

    Attributes:
        id - the UUID primary key of the FollowRequest
        summary - a short note to be sent with the FollowRequest
        follower - the sender of the FollowRequest
        following - the recipient of the FollowRequest
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    summary = models.CharField(max_length=200)
    follower = models.ForeignKey(Author, related_name='outgoing_follow_requests', on_delete=models.CASCADE)
    following = models.ForeignKey(Author, related_name='incoming_follow_requests', on_delete=models.CASCADE)


class Post(models.Model):
    """
    A class representing a post made by an author.
    Can be viewed, liked, commented on, or shared.

    Attributes:
        title - the title of the Post
        id - the UUID primary key of the Post
        source - the link from where this Post was received
        origin - the link from which this Post originated
        description - a description of the post
        contentType - the content format of the post
            - can be plaintext, markdown or image?
        content - the post text
        author - the author that created the post
        categories - list of categories that the post fits into
        count - the total number of comments on the post
        published - the ISO 8601 timestamp when the post was published
        visibility - one of PUBLIC, PRIVATE, or FRIENDS ONLY; determines who can see the post
        unlisted - flag whether the post is discoverable by browsing
    """

    class VisibilityChoice(models.TextChoices):
        PUBLIC = "PUBLIC", "PUBLIC"
        PRIVATE = "PRIVATE", "PRIVATE"
        FRIENDS_ONLY = "FRIENDS_ONLY", "FRIENDS_ONLY"

    class TypeChoice(models.TextChoices):
        TEXT = "text/plain", "Text"
        COMMON = "text/markdown", "CommonMark"
        IMAGE = "image/png;base64", "PNG"
        IMAGE2 = "image/jpeg;base64", "JPEG"
    
    type = models.CharField(max_length=20, default="post")
    title = models.CharField(max_length=50, default="Untitled")
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    source = models.URLField(max_length=200, blank=True)
    origin = models.URLField(max_length=200, blank=True)
    description = models.CharField(max_length=50, default="")
    private_reciever = models.ForeignKey(Author, related_name="reciever", blank=True, null=True, default=None, on_delete=models.CASCADE)  # TODO should we allow post to remain if reciever author is deleted? if not, what else do we do?
    contentType = models.CharField(max_length=200, choices=TypeChoice.choices)
    content = models.TextField(default="")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    categories = models.CharField(max_length=200, default="") # TODO Change to list
    count = models.IntegerField(default=0)
    published = models.DateTimeField(default=timezone.now, blank=True)
    visibility = models.CharField(max_length=50, choices=VisibilityChoice.choices, default=VisibilityChoice.PUBLIC)
    unlisted = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse("project:post", kwargs={"author_id": self.author,"pk": self.pk})
    
    def get_url(self):
        return f"{self.author.get_url()}/posts/{self.id}"
    

class Comment(models.Model):
    """
    Class representing a comment on a post.

    Attributes:
        author - the author who wrote the comment
        comment - the content of the comment
        contentType - the format of the comment
            - can be plaintext or markdown
        published - the ISO 8601 timestamp when the comment was posted
        id - the UUID primary key of the comment
        post - the post that the comment was added too
    """

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment = models.TextField(max_length=600)
    contentType = models.CharField(max_length=200)
    published = models.DateTimeField(default=timezone.now, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def get_url(self):
        return f"{self.post.get_url()}/comments/{self.id}"

class PostLike(models.Model):
    """
    Class representing a like on a post.

    Attributes:
        context - ??? (http://niem.github.io/json/reference/json-ld/context/)
        summary - a short note sent with the like
        author - the author who liked the post
        post - the post that was liked
        id - the UUID primary key of the like
    """
    context = models.URLField(max_length=200)
    summary = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


class CommentLike(models.Model):
    """
    Class representing a like on a comment.

    Attributes:
        context - ??? (http://niem.github.io/json/reference/json-ld/context/)
        summary - a short note sent with the like
        author - the author who liked the comment
        comment - the comment that was liked
        id - the UUID primary key of the like
    """
    context = models.URLField(max_length=200)
    summary = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


class Node(models.Model):
    """
    A class representing a node running the distributed social network.

    Attributes:
        id - the UUID primary key of the node
        nodeName - the name of the node
        apiURL - the address to access the API service
        host - the IP of the node
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nodeName = models.CharField(max_length=50, blank=True)
    nodeCred = models.CharField(max_length=50, blank=True)
    apiURL = models.URLField(max_length=200, blank=True)
    host = models.CharField(max_length=200, default="127.0.0.1:8000")

socialDistribution/project/templates/project/author.html
{% load static %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">

<h1>{{ author.displayName }}</h1>

{% if author.post_set.all %}
    <ul>
    {% for post in author.post_set.all %}
        <li class="post">
            <h3><a href="{% url 'project:post' post.author.id post.id %}">{{ post.title }}</a></h3>

            <p>{{ post.content }}</p>

            <p>0 &#x1F44D 0 &#128172</p>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

socialDistribution/project/templates/project/create-post.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Create Post{% endblock %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">
<head>
  
  <script>

    function checkFormVals(value){
      console.log(value.selectedOptions[0].value)
      if (value.selectedOptions[0].value == 'text/plain' || value.selectedOptions[0].value == 'text/markdown'){
        document.getElementById("content").style.display = 'block';
        document.getElementById("picture").style.display = 'none';
      }
      else{
        document.getElementById("content").style.display = 'none';
        document.getElementById("picture").style.display = 'block';
      }
    }

  </script>
</head>
<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<form method="POST" enctype="multipart/form-data" autocomplete="off" id="myForm">
    {% csrf_token %}
    {{form.non_field_errors}}
    
    <p>Type:</p>{% render_field form.contentType onchange='checkFormVals(form.contentType)' %}
    <p id="content">Content: {{ form.content }}</p>
    <p id="picture" style="display: none;">Image Upload: {{ form.picture }}</p>
    <p id="title" on>Title: {{ form.title }}</p>
    <p id="desc">Description: {{ form.description }}</p>
    <p id="cat">Categories: {{ form.categories }}</p>
    <p id="vis">Visibility: {{ form.visibility }}</p>
    <p id="unlist">Unlisted: {{ form.unlisted }}</p>

 
    <button form="myForm" type="submit" value="Submit">Create</button>
</form>
{% endblock %}

socialDistribution/project/templates/project/edit-post.html
{% load static %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">

<h1>Edit Post</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" value="Submit">Submit</button>
</form>

socialDistribution/project/templates/project/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <!-- The following are examples to reference user and author data. -->
    <div class="task_bar">
      <div>
          <button type="button" id="search">
              <a id="search_a" href="{% url 'project:search' %}">Search</a>
            </button>
            <button type="button" id="profile">
              <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
            </button>
            <button type="button" id="post">
              <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
            </button>
            <button type="button" id="home">
              <a id="home_a"href="{% url 'project:home' %}">Home</a>
              </button>
      </div>
      <div class="right_nav">
          <button type="button" id="settings">
              <a id="set_a">Settings</a>
          </button>
          <button type="button" id="logout">
              <a id="log_a" href="{% url 'logout' %}">Logout</a>
          </button>
          
      </div>
    </div>
  <h1>Hi {{ user.username }}!</h1>
  <h1>Hi {{ user.author.displayName }}!</h1>
  <h1>Check me out on Github: {{ user.author.github }}</h1>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

socialDistribution/project/templates/project/post.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% load static %}
<script>

function shouldConvert(post){
    if (text.contains("base:image")){
        return true
    }
    return false
}

function baseToImage(base64){
    if (base64.contains("base:image")){
        image = atob(base64)
    }
    return image
}
function ImageToBase(image){
    base = btoa(image)
    return base
}

</script>>


<link rel="stylesheet" href="{% static 'project/base.css' %}">
<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<div class="post-popup">
    <h1>{{ post.title }}</h1>
   
    <h3><a href="{% url 'project:profile' post.author.id %}">{{ post.author.displayName }}</a></h3>
        
        {% if post.contentType == "image/png;base64" or post.contentType == "image/jpeg;base64" or post.contentType == "image/jpeg;base64" %}
        <img src="{{post.content}}" alt="pic" style="max-width: 200px; max-height: 200px;">
        {% else %}
        <p>{{ post.content }}</p>
        {% endif %}
    <p>{{ post.postlike_set.count }} &#x1F44D; {{ post.comment_set.count }} &#128172;</p>

    <!-- Like Button -->
    <form method="post" action="{% url 'project:like_post' post.author.id post.id %}">
        {% csrf_token %}
        <button type="submit">Like</button>
    </form>

    <!-- Update Post -->
    {% if user.is_authenticated and user.author.id == post.author.id%}
        <form action="{% url 'project:edit-post' post.id %}">
            <button type="submit">Edit Post</button>
        </form>
    {% endif %}

    <h2>Comments</h2>

    {% if post.comment_set.all %}
        {% for comment in post.comment_set.all %}
            <div class="comment">
                <h3><a href="{% url 'project:profile' comment.author.id %}">{{ comment.author.displayName }}</a></h3>
                <p>{{ comment.comment }}</p>

                <p>{{ comment.commentlike_set.count }} &#x1F44D;</p>
                <form method="post" action="{% url 'project:like_comment' comment.id %}">
                    {% csrf_token %}
                    <button type="submit">Like</button>
                </form>
            </div>
        {% endfor %}
    {% else %}
        <p>No comments are available.</p>
    {% endif %}

    <!-- Comment Form -->
    <form method="post" action="{% url 'project:add_comment' post.author.id post.id %}">
        {% csrf_token %}
        <textarea name="content" placeholder="Add a comment..."></textarea>
        <button type="submit">Comment</button>
    </form>
    <form method="post" action="{% url 'project:post_delete' post.author.id post.id %}">
        {% csrf_token %}
    {%if post.author.id == user.author.id%}
    <button type="submit">DELETE</button>
    {%endif%}
    </form>
</div>
{% endblock %}

socialDistribution/project/templates/project/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}


<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<div class = "user-profile">
    <!-- Note: remove hardcoded properties for image -->
    
    <img src={{ author.profileImage }} alt="user profile image" width="100" height="100">

        <h1 id = "disp">{{ author.displayName }}</h1>
        <a id="git" href="http://{{ author.github }}">Check me out on Github</a>
    
        <h4 id="bio">{{ author.bio }}</h4>    


</div>

<br></br>

<div class = "posts">
    <h4>Posts</h4>
    {% if author.post_set.all %}
    <ul>
    {% for post in author.post_set.all %}
        <li class="post">
            <h3><a href="{% url 'project:post' post.author.id post.id %}">{{ post.title }}</a></h3>

            
        {% if post.contentType == "image/png;base64" or post.contentType == "image/jpeg;base64" or post.contentType == "image/jpeg;base64" %}
        <img src="{{post.content}}" alt="pic" style="max-width: 200px; max-height: 200px;">
        {% else %}
        <p>{{ post.content }}</p>
        {% endif %}
            <p>{{ post.postlike_set.count }} &#x1F44D {{ post.comment_set.count }} &#128172</p>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}
</div>
<h4> Followers:</h4>
<div class = "followers">
    <ul>
        {% for follow in author.followers.all %}
    <li>
        <a href="{% url 'project:profile' follow.id %}">{{follow.displayName}}</a>
    </li>
    {%endfor%}
    </ul>
    
</div>

<div class = "github-activity">
    <h4>Github Activity</h4>
</div>

<form method="post" action="{% url 'project:follow' author.id %}">
    {% csrf_token %}
    {% if user.is_authenticated %}
    {% if author.displayName != user.author.displayName %}
    <button type="submit">Follow</input>
    {%endif%}
    {%endif%}
</form>

 {% endblock %}

socialDistribution/project/templates/project/stream.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">
<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<h1>Stream/Inbox Page</h1>

  

<div class="user-profile">
    <img src={{ author.profileImage }} alt="User Image">
    <div class="user-details">
        <h2 id="stream-name">{{user.author.displayName}}</h2>
        <p>Welcome to SocialDistribution! Make posts, explore other user profiles, and make friends.</p>
        <button>Settings</button>
    </div>
</div>

<div class="user-posts">
    {% if latest_posts %}
        {% for post in latest_posts %}
            <div class="post">
                <h3><a href="{% url 'project:post' post.author.id post.id %}">{{ post.title }}</a></h3>
                <p>{{ post.content }}</p>
                <p>{{ post.postlike_set.count }} &#x1F44D; {{ post.comment_set.count }} &#128172;</p>
            </div>
        {% endfor %}
    {% else %}
        <p>There is no activity in your feed...</p>
    {% endif %}
</div>


<div class="inbox">
    <h2>Inbox</h2>
    <!-- Friend request processing -->
    <h3>Friend Requests</h3>
    <ul>
        {% for fr in user.author.incoming_follow_requests.all %}
            <li>
                {{ fr.follower.displayName }} wants to follow you. 
    
                <!-- Accept Follow Form -->
                <form method="post" action="{% url 'project:accept_follow' fr.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Accept</button>
                </form> |
    
                <!-- Decline Follow Form -->
                <form method="post" action="{% url 'project:decline_follow' fr.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Decline</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    
</div>
{% endblock %}